### ISSUE TITLE
Don't know how to build task 'uploader:install:migrations'

### ISSUE THREAD

**Issue by antoniobg** [superp/rails-uploader#13]
Hey, I'm getting this error when I try to run "rake uploader:install:migrations". The gem is successfully installed and I also edit the routes file. What could be the problem?

**Comment by kalashnikovisme** [comment]
@antoniobg https://github.com/tbprojects/rails-uploader this fork looks like that works with Rails 4.0

**Comment by antoniobg** [comment]
Thanks @kalashnikovisme
