### ISSUE TITLE
No relevant rake tasks after gem installation 

### ISSUE THREAD

**Issue by grBro** [superp/rails-uploader#17]
Hi!

`rake --tasks` doesn't show `uploader:install:migrations` after successfull gem installation.

Rails version 4.2.6

**Comment by hjansen** [comment]
Same problem here ...

**Comment by noise2** [comment]
same problem here... what is wrong??

**Comment by alexanderadam** [comment]
Should be fixed now.
[But instead a `rake` task it is `bundle exec rails g uploader:install`](https://github.com/superp/rails-uploader#install)

**Comment by superp** [comment]
@alexanderadam big thanks!
