### ISSUE TITLE
undefined method `merge_wrapper_options' for #<SimpleForm::Inputs::UploaderInput:…>

### ISSUE THREAD

**Issue by alexanderadam** [superp/rails-uploader#19]
I tried to include rails-uploader on a legacy project and I get an exception with simple_form 3.0.1 when calling `f.input :file, as: :uploader` 😞

**Comment by superp** [comment]
You can find answer [here](https://stackoverflow.com/a/26331237/355444)

**Comment by alexanderadam** [comment]
thank you
