### ISSUE TITLE
NoMethodError (undefined method `mount_uploader' for Picture:Class):

### ISSUE THREAD

**Issue by pmaojo** [superp/rails-uploader#26]
Im trying to implement the example on readme.md but get this error.

NoMethodError (undefined method `mount_uploader' for Picture:Class):

![captura de pantalla 2018-06-19 12 42 57](https://user-images.githubusercontent.com/411551/41595337-53d386ea-73be-11e8-9104-b299dc507234.png)

**Comment by superp** [comment]
you forget to insert:
`include Uploader::Asset`
