### ISSUE TITLE
How to use sortable?

### ISSUE THREAD

**Issue by pmaojo** [superp/rails-uploader#28]
I have the input like:
<%= form.input :pictures, as: :uploader, input_html: { sortable: true } %>
inside a simple_form

Everything is working but the sort_order is not saving on database, what could I be missing? 

I have this code in Asset model: 

```
  def to_fileupload
    {
      id: id,
      name: data_file_name,
      content_type: data_content_type,
      size: data_file_size,
      thumb_url: thumb_url,
      sort_order: sort_order
    }
  end 

```
help please.

I also tried to add sort_order to the params on the attachments_controller.rb in the gem.:_

```
    def asset_params
      ActionController::Parameters.new(params).require(:asset).permit(:data, :sort_order)
    end
```

**Comment by superp** [comment]
This gem doesn't support sorting, you must write your own controller for this.

**Comment by pmaojo** [comment]
I see there is this code:

`      def fileupload_update_ordering(params)
        return if params[:assets].blank?

        Array(params[:assets]).each_with_index do |id, index|
          where(id: id).update_all(sort_order: index)
        end
      end
`

I can call this from a controller, right?

**Comment by pmaojo** [comment]
There is no request. No ajax call seems to be triggering. 
I think that there might be a detail to correct regarding the drag and drop plugin events to make it fire the ajax call

**Comment by pmaojo** [comment]
by the way, thankyou very much for help and this gem

**Comment by pmaojo** [comment]
Changing the javascript made it work:

```
  $(function() {
    var container, data;

    container = $("#<%= field.id %> div.uploader-files");

    container.sortable({
      placeholder: "attach_item",
      cursor: "move",
      update: function(event, ui) {
        data = $(this).sortable("serialize", {key: "assets[]"});
        $.ajax({
          url: "<%= uploader.attachment_path(field.klass) %>",
          type: "PUT",
          dataType: "json",
          data: data + "&klass=<%= field.klass %>"
        });
      }
    });

    container.disableSelection();
  });

```

**Comment by pmaojo** [comment]
`$.rails.ajax `to `$.ajax`
